export const ANSWER_PAGE_INDEX_GET = 'ANSWER_PAGE_INDEX_GET'
export const ANSWER_PAGE_INDEX_SET = 'ANSWER_PAGE_INDEX_SET'
export const ANSWER_PAGE_LIST_GET = 'ANSWER_PAGE_LIST_GET'
export const ANSWER_PAGE_LIST_SET = 'ANSWER_PAGE_LIST_SET'