export const PAGE_INDEX_GET = 'PAGE_INDEX_GET'
export const PAGE_INDEX_SET = 'PAGE_INDEX_SET'
export const PAGE_INDEX_UPPER = 'PAGE_INDEX_UPPER'
export const PAGE_INDEX_LOWER = 'PAGE_INDEX_LOWER'
export const PAGE_INDEX_CLEAR = 'PAGE_INDEX_CLEAR'

export const PAGE_INDEX_DETAIL_SET = 'PAGE_INDEX_DETAIL_SET'
export const API_LAST_PAGE_NUM = 'API_LAST_PAGE_NUM'
export const API_UPDATE_PAGE_NUM = 'API_UPDATE_PAGE_NUM'


